[package]
name = "rssc-intract"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = { version = "0.5.0-rc.2", features = ["json"] }
jsonwebtoken = "8"
serde = { version = "1", features = ["derive"] }
clap="4"
