[frontend]
# file path to frontend
# this is where your index.html lives
location = 'web'

[web]
port = 6969
address = "127.0.0.1"

[log]
# Path to log
path = "/tmp/intract.log"

# Max size of log, in mb.
size = 5

# Lowest log level to print to console
# Off, Error, Warn, Info, Debug, Trace
# Default: Info
console_level = "Info"

# Lowest log level in log file
# Default: Trace
file_level = "Trace"

[security]
# used for encrypting cookies
secret_key = "hPRYyVRiMyxpw5sBB1XeCMN1kFsDCqKvBi2QJxBVHQk="
