[frontend]
location = 'web'

[web]
port = 4000
address = '127.0.0.1'

[log]
path = '/tmp/intract.log'
size = 5.0
# these levels can be INFO TRACE WARNING or ERROR
console_level = 'INFO'
file_level = 'INFO'

[privacy]
# this tells search engines if they're allowed to index your site
robots_txt = 'User-agent: *\nDisallow: /'

[privacy]
robots_txt = "User-agent: *\nDisallow: /"

[security]
# you should probably generate your own when running this
secret_key = 'hPRYyVRiMyxpw5sBB1XeCMN1kFsDCqKvBi2QJxBVHQk='

[database]
url = 'postgres://username:password@localhost/database'